version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - table-data:/var/lib/postgres/data
  app:
    build: .
    working_dir: /web/web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/web
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes: 
      - db-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes: 
  db-data:
  table-data: