"""create database

Revision ID: 466d76466fd4
Revises: 
Create Date: 2022-11-09 18:10:12.449041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466d76466fd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product', sa.String(length=1150), nullable=True),
    sa.Column('link', sa.String(length=2150), nullable=True),
    sa.Column('image', sa.String(length=1150), nullable=True),
    sa.Column('price', sa.String(length=1150), nullable=True),
    sa.Column('priceSale', sa.String(length=1150), nullable=True),
    sa.Column('color', sa.String(length=1150), nullable=True),
    sa.Column('size', sa.String(length=1150), nullable=True),
    sa.Column('description', sa.String(length=1150), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provinces_id'), 'provinces', ['id'], unique=False)
    op.create_index(op.f('ix_provinces_province'), 'provinces', ['province'], unique=True)
    op.create_table('shops',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_id'), 'shops', ['id'], unique=False)
    op.create_index(op.f('ix_shops_link'), 'shops', ['link'], unique=True)
    op.create_index(op.f('ix_shops_shop'), 'shops', ['shop'], unique=True)
    op.create_table('categories',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('shopId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shopId'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category'), 'categories', ['category'], unique=True)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_link'), 'categories', ['link'], unique=True)
    op.create_table('districts',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=200), nullable=True),
    sa.Column('provinceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provinceId'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_district'), 'districts', ['district'], unique=True)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_table('labels',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_id'), 'labels', ['id'], unique=False)
    op.create_index(op.f('ix_labels_label'), 'labels', ['label'], unique=True)
    op.create_index(op.f('ix_labels_link'), 'labels', ['link'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Village', sa.String(length=200), nullable=True),
    sa.Column('provinceId', sa.Integer(), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['provinceId'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_Village'), 'villages', ['Village'], unique=True)
    op.create_index(op.f('ix_villages_id'), 'villages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_villages_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_Village'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_labels_link'), table_name='labels')
    op.drop_index(op.f('ix_labels_label'), table_name='labels')
    op.drop_index(op.f('ix_labels_id'), table_name='labels')
    op.drop_table('labels')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_district'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_categories_link'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_category'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_shops_shop'), table_name='shops')
    op.drop_index(op.f('ix_shops_link'), table_name='shops')
    op.drop_index(op.f('ix_shops_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_provinces_province'), table_name='provinces')
    op.drop_index(op.f('ix_provinces_id'), table_name='provinces')
    op.drop_table('provinces')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
