"""update idlabel

Revision ID: 4b430fae3576
Revises: 9e569ea5da68
Create Date: 2022-11-16 16:46:18.022312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b430fae3576'
down_revision = '9e569ea5da68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_labelId_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'labelId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('labelId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_labelId_fkey', 'products', 'labels', ['labelId'], ['id'])
    # ### end Alembic commands ###
