"""create image

Revision ID: 55974a6907f7
Revises: eb56cd566581
Create Date: 2022-11-29 05:03:48.485546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55974a6907f7'
down_revision = 'eb56cd566581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('showProducts', sa.Column('image', sa.String(length=1200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('showProducts', 'image')
    # ### end Alembic commands ###
