"""update labelid null

Revision ID: 6c9ee614ae99
Revises: 9a30615a1fe9
Create Date: 2022-11-20 16:27:19.123004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9ee614ae99'
down_revision = '9a30615a1fe9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
