"""update image

Revision ID: 769c2d6f7096
Revises: 466d76466fd4
Create Date: 2022-11-09 18:19:13.662700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769c2d6f7096'
down_revision = '466d76466fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.VARCHAR(length=1150),
               type_=sa.String(length=5000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=1150),
               existing_nullable=True)
    # ### end Alembic commands ###
