"""create data

Revision ID: 960fd020c7c6
Revises: f216e343d19b
Create Date: 2022-11-14 10:27:50.921510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960fd020c7c6'
down_revision = 'f216e343d19b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
