"""update data

Revision ID: 9a30615a1fe9
Revises: c3234ef79432
Create Date: 2022-11-20 09:16:50.312777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a30615a1fe9'
down_revision = 'c3234ef79432'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('labelId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'labels', ['labelId'], ['id'])
    op.add_column('showProducts', sa.Column('labelId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'showProducts', 'labels', ['labelId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'showProducts', type_='foreignkey')
    op.drop_column('showProducts', 'labelId')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'labelId')
    # ### end Alembic commands ###
