"""update_show_product_id-null

Revision ID: c3234ef79432
Revises: 4b430fae3576
Create Date: 2022-11-17 16:25:16.366097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3234ef79432'
down_revision = '4b430fae3576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
