"""add column categoryId for table Labels

Revision ID: eb56cd566581
Revises: 3487f107e9b6
Create Date: 2022-11-26 15:19:48.614803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb56cd566581'
down_revision = '3487f107e9b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('categoryId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'labels', 'categories', ['categoryId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_column('labels', 'categoryId')
    # ### end Alembic commands ###
