"""create data

Revision ID: f216e343d19b
Revises: 069fc80e4782
Create Date: 2022-11-14 10:26:00.117693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f216e343d19b'
down_revision = '069fc80e4782'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_labelId_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_id_district_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'labelId')
    op.drop_column('products', 'id_district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('id_district', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('labelId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_id_district_fkey', 'products', 'districts', ['id_district'], ['id'])
    op.create_foreign_key('products_labelId_fkey', 'products', 'labels', ['labelId'], ['id'])
    # ### end Alembic commands ###
